# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 16:36
from __future__ import unicode_literals

import deux.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deux', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='multifactorauth',
            name='qrcode_secret',
            field=models.CharField(help_text='Encoded Secret Key', max_length=32),
        ),
        migrations.AlterField(
            model_name='multifactorauth',
            name='challenge_type',
            field=models.CharField(blank=True, choices=[('sms', 'SMS'), ('qrcode', 'QRCODE'), ('', 'Off')], default='', max_length=16),
        ),
    ]
