# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import pyotp


class Migration(migrations.Migration):

    dependencies = [
        ('deux', '0002_auto_20170713_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multifactorauth',
            name='qrcode_secret',
        ),
        migrations.RemoveField(
            model_name='multifactorauth',
            name='sms_secret_key',
        ),
        migrations.AddField(
            model_name='multifactorauth',
            name='secret_key',
            field=models.CharField(default=pyotp.random_base32, help_text='Hex-Encoded Secret Key', max_length=32),
        ),
    ]
