# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 16:22
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import pyotp
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deux', '0003_auto_20170714_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupPhoneAuth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Please enter a valid phone number.', regex='^(\\d{7,15})$')])),
                ('secret_key', models.CharField(default=pyotp.random_base32, help_text='Hex-Encoded Secret Key', max_length=32)),
                ('method', models.CharField(choices=[('call', 'Phone Call'), ('sms', 'Text Message')], default='sms', max_length=4, verbose_name='method')),
                ('confirmed', models.BooleanField(default=False, help_text='Is this device ready for use?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
