# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 16:02
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('deux', '0004_backupphoneauth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupphoneauth',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128),
        ),
        migrations.AlterField(
            model_name='multifactorauth',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128),
        ),
    ]
